-- Backfills roster_entries.school for players who skipped college,
-- resolved from the NBA stats API scrape already in DataScraping/data/roster/raw/*.json.
-- Generated automatically; review before running.

UPDATE roster_entries SET school = 'Filathlitikos' WHERE player_id = 'antetgi01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Panathinaikos' WHERE player_id = 'antetth01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Maccabi Tel Aviv' WHERE player_id = 'avdijde01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'FC Barcelona' WHERE player_id = 'badjiib01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Illawarra' WHERE player_id = 'ballla01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Overtime Elite' WHERE player_id = 'barlodo01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Le Mans' WHERE player_id = 'batumni01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Princeton HS (OH)' WHERE player_id = 'bazleda01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Baskonia' WHERE player_id = 'bertada01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Mega Basket' WHERE player_id = 'bitadgo01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Bursaspor' WHERE player_id = 'bitimon01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Baloncesto Fuenlabrada' WHERE player_id = 'biyombi01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Fenerbahce' WHERE player_id = 'bjeline01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Fenerbahce' WHERE player_id = 'bogdabo01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Fenerbahce' WHERE player_id = 'bogdabo02' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'FC Barcelona' WHERE player_id = 'bolmale01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Skyliners Frankfurt' WHERE player_id = 'bongais01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'NBA G League Ignite' WHERE player_id = 'buzelma01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Murcia' WHERE player_id = 'campafa01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'San Pablo Burgos' WHERE player_id = 'cancavl01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Elan Chalon' WHERE player_id = 'capelca01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'NBA Global Academy' WHERE player_id = 'chomcul01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'NBA G League Ignite' WHERE player_id = 'cissosi01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Metropolitans 92' WHERE player_id = 'coulibi01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Ratiopharm Ulm' WHERE player_id = 'dadiepa01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'NBA G League Ignite' WHERE player_id = 'daniedy01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'New Zealand Breakers' WHERE player_id = 'diengou01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Real Madrid' WHERE player_id = 'doncilu01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Union Olimpija' WHERE player_id = 'dragigo01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Victoria Libertas' WHERE player_id = 'drellhe01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Australian Institute of Sport' WHERE player_id = 'exumda01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Adelaide' WHERE player_id = 'flowetr01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Baskonia' WHERE player_id = 'fontesi01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Poitiers Basket 86' WHERE player_id = 'fournev01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Olimpia Milano' WHERE player_id = 'gallida01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Real Madrid' WHERE player_id = 'garubus01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'NBA Global Academy' WHERE player_id = 'giddejo01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Cholet' WHERE player_id = 'goberru01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Real Madrid' WHERE player_id = 'gonzahu01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'NBA G League Ignite' WHERE player_id = 'greenja05' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Capital City Go-Go' WHERE player_id = 'hamptrj01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'NBA G League Ignite' WHERE player_id = 'hardyja02' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Zalgiris' WHERE player_id = 'harteis01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Ratiopharm Ulm' WHERE player_id = 'hayeski01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'NBA G League Ignite' WHERE player_id = 'hendesc01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Estudiantes' WHERE player_id = 'hernaju01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Cajasol Sevilla' WHERE player_id = 'hernawi01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'SW Atlanta Christian Academy (GA)' WHERE player_id = 'howardw01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Riesen Ludwigsburg' WHERE player_id = 'hukpoar01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Ricoh Manresa' WHERE player_id = 'ibakase01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Maccabi Tel Aviv' WHERE player_id = 'inglejo01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'St. Vincent-St. Mary HS (OH)' WHERE player_id = 'jamesle01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Illawarra' WHERE player_id = 'johnsaj01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Mega Basket' WHERE player_id = 'jokicni01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Mega Basket' WHERE player_id = 'jovicni01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Yokohama B-Corsairs (Japan)' WHERE player_id = 'kawamyu01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Bayern Munich' WHERE player_id = 'klebima01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Anadolu Efes' WHERE player_id = 'korkmfu01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Zaragoza' WHERE player_id = 'krejcvi01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Bilbao' WHERE player_id = 'kulboar01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'NBA G League Ignite' WHERE player_id = 'kuminjo01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Sydney' WHERE player_id = 'louzama01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'CSKA Moscow' WHERE player_id = 'lundbga01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Mega Basket' WHERE player_id = 'luwawti01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'ASVEL' WHERE player_id = 'maledth01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Crvena zvezda' WHERE player_id = 'marjabo01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Overtime Elite' WHERE player_id = 'martija02' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'IMG Academy (FL)' WHERE player_id = 'martike04' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Mega Basket' WHERE player_id = 'matkoka01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Serbia' WHERE player_id = 'micicva01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'NBA G League Ignite' WHERE player_id = 'millele01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Murcia' WHERE player_id = 'netora01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'NBA G League Ignite' WHERE player_id = 'nixda01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Strasbourg IG' WHERE player_id = 'ntilila01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Cedevita' WHERE player_id = 'nurkiju01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Anadolu Efes' WHERE player_id = 'osmande01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Le Mans Sarthe' WHERE player_id = 'pendano01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Olympiacos' WHERE player_id = 'pokusal01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Cajasol Sevilla' WHERE player_id = 'porzikr01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'JL Bourg-en-Bresse' WHERE player_id = 'risacza01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'FC Barcelona' WHERE player_id = 'rubiori01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'New Zealand Breakers' WHERE player_id = 'ruperra01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Cholet' WHERE player_id = 'salauti01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Union Olimpija' WHERE player_id = 'samanlu01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Minas' WHERE player_id = 'santogu01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Ratiopharm Ulm' WHERE player_id = 'sarafbe01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Anadolu Efes' WHERE player_id = 'saricda01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Washington Wizards' WHERE player_id = 'sarral01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'FC Barcelona' WHERE player_id = 'satorto01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Braunschweig' WHERE player_id = 'schrode01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Besiktas' WHERE player_id = 'sengual01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Edgewater HS (FL)' WHERE player_id = 'simonan01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Mega Basket' WHERE player_id = 'simonma01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'NBA G League Ignite' WHERE player_id = 'smithty02' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Brose Bamberg' WHERE player_id = 'theisda01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Overtime Elite' WHERE player_id = 'thompam01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Overtime Elite' WHERE player_id = 'thompau01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'G League Ignite' WHERE player_id = 'toddis01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Crvena zvezda' WHERE player_id = 'topicni01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Saint-Quentin' WHERE player_id = 'traorno01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Rockingham Flames (Aus.)' WHERE player_id = 'travelu01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Lietuvos rytas Vilnius' WHERE player_id = 'valanjo01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Barcelona, Spain' WHERE player_id = 'vezenal01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Real Madrid' WHERE player_id = 'vukcetr01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Metropolitans 92' WHERE player_id = 'wembavi01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'South Gwinnett HS (GA)' WHERE player_id = 'willilo02' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Rouen, France' WHERE player_id = 'yabusgu01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Zibo' WHERE player_id = 'yangha01' AND (school IS NULL OR school = '');
UPDATE roster_entries SET school = 'Mega Basket' WHERE player_id = 'zubaciv01' AND (school IS NULL OR school = '');
