export type Team = {
  teamId: string;
  teamName: string;
  year: string;
  team: string;

  gp: number;
  w: number;
  l: number;
  min: number;
  fgm: number;
  fga: number;
  fg3m: number;
  fg3a: number;
  ftm: number;
  fta: number;
  oreb: number;
  dreb: number;
  reb: number;
  ast: number;
  tov: number;
  stl: number;
  blk: number;
  blka: number;
  pf: number;
  pfd: number;
  pts: number;
  plusMinus: number;
  offRating: number;
  defRating: number;
  netRating: number;
  astTo: number;
  astRatio: number;
  pace: number;
  pacePer40: number;
  poss: number;
  pie: number;
  oppFgm: number;
  oppFga: number;
  oppFg3m: number;
  oppFg3a: number;
  oppFtm: number;
  oppFta: number;
  oppOreb: number;
  oppDreb: number;
  oppReb: number;
  oppAst: number;
  oppTov: number;
  oppStl: number;
  oppBlk: number;
  oppBlka: number;
  oppPf: number;
  oppPfd: number;
  oppPts: number;

  winPct: number | null;
  fgPct: number | null;
  fg3Pct: number | null;
  ftPct: number | null;
  astPct: number | null;
  orebPct: number | null;
  drebPct: number | null;
  rebPct: number | null;
  tmTovPct: number | null;
  efgPct: number | null;
  tsPct: number | null;
  oppFgPct: number | null;
  oppFg3Pct: number | null;
  oppFtPct: number | null;
};
